### PR TITLE
Created Sample flask app

### PR DESCRIPTION
**Pull request by nishant-sethi**

### CODE REVIEW

**Comment by nishant-sethi** [comment]
@rafaelhenrique let me try it again

**Comment by rafaelhenrique** [comment]
@nishant-sethi i comment on issue ... if do you have any questions call me :wink: 

Thanks!

**Comment by rafaelhenrique** [comment]
Whats the purpouse of commit ab1c4df  @nishant-sethi ?

**Comment by rafaelhenrique** [comment]
So... if you have questions please send me @nishant-sethi ... for now i close this PR. Thanks!

**Pull request closed without merging**
